-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 06-09-2020 a las 00:00:21
-- Versión del servidor: 10.4.13-MariaDB
-- Versión de PHP: 7.4.8

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `id13080475_basedatosprueba`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `articulos`
--

CREATE TABLE `articulos` (
  `CODIGO` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL,
  `NOMBREARTICULO` varchar(250) COLLATE utf8_unicode_ci DEFAULT NULL,
  `URL` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `DESCRIPCION` longtext COLLATE utf8_unicode_ci DEFAULT NULL,
  `FOTO` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `TAGS` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `FECHA` varchar(11) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ID` int(11) NOT NULL,
  `CONTENIDO` longtext COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Volcado de datos para la tabla `articulos`
--

INSERT INTO `articulos` (`CODIGO`, `NOMBREARTICULO`, `URL`, `DESCRIPCION`, `FOTO`, `TAGS`, `FECHA`, `ID`, `CONTENIDO`, `created_at`) VALUES
('AR01', 'ARTICULO ACTUALIZACIONES', 'Articulos/articulo%20actualizaciones.html', 'Actualizaciones IOS, Whatsapp, aumento en los precios de los componentes de PCs', 'articulosThumb/wifi1.jpg', 'precios, pc, whatsapp, apple, android, smartphone, noticias, ssd, ssds, informatica, aumento, covid, covid-19, coronavirus, corona virus, informacion, adobe, photoshop, ios', NULL, 1, NULL, '2020-09-05 21:56:18'),
('AR02', 'ARTICULO S20', 'Articulos/articulo%20s20.html', 'Review del ultimo telefono de Samsung Galaxy S20', 'articulosThumb/s20ultra.jpg', 'samsung, s20, telefonos, telefonos, smartphones, celulares, celular, smartphone, tecnologia, reviews, review, galaxy, samsung galaxy, s20 ultra', NULL, 2, NULL, '2020-09-05 21:56:18'),
('AR03', 'ARTICULO MEJORA WIFI', 'Articulos/articulo%20wifi.html', 'Mejorar el internet que recibís por conexión inalámbrica, de forma sencilla, segura y gratis.', 'articulosThumb/wifi3.jpg', 'informatica, redes, mejorar, internet, wifi, router, routers, configurar, instalar, velocidad, red, canales, frecuencia', NULL, 3, NULL, '2020-09-05 21:56:18'),
('AR04', 'ARTICULO APRENDER PROGRAMAR', 'Articulos/articulo%20programacion.html', 'Consejos para todos os que quieran introducirse en el mundo de la programación.', 'articulosThumb/codigo3.jpg', 'programacion, developers, java, python, c, c++, c#, poo, objetos, programacion objetos, programacion orientada a objetos, desarrollo, html, javascript, css, 5, 3, programar', NULL, 4, NULL, '2020-09-05 21:56:18'),
('AR05', 'ARTICULO nueva Nvidea', 'Articulos/articulo%20nvidea.html', 'Se rumorea que podría lanzarse en agosto una RTX 3090.', 'articulosThumb/gforce.jpg', 'juegos, gaming, nvidea, nuevo, nueva generacion, geforce, gforce, gamers, gaming, videojuegos, estrenos, amd, review, reviews, rumores, tarjeta grafica, placa de video', NULL, 5, NULL, '2020-09-05 21:56:18'),
('AR06', 'ARTICULO HUAWEI', 'Articulos/articulo%20huawei.html', 'Huawei, nuevo teléfono y Asistente Virtual.', 'articulosThumb/p40.jpg', 'huawei, p40, telefonos, telefonos, smartphones, celulares, celular, smartphone, tecnologia, reviews, review, p40 pro', NULL, 6, NULL, '2020-09-05 21:56:18'),
('AR07', 'ARTICULO INTEL VS COVID19', 'Articulos/articulo%20covid.html', 'Intel dono 1 millón de elementos de protección a médicos que están combatiendo el Coronavirus.', 'articulosThumb/intel.png', 'computacion, intel, empresas, covid, covid-19, covid19, corona, corona virus, medicos, medicina, enfermeros, proteccion, epi, donacion, donar, computadoras, pc, razor, apple', NULL, 7, NULL, '2020-09-05 21:56:18'),
('AR08', 'ARTICULO Android 11', 'Articulos/articulo%20android11.html', 'Google anunció el lanzamiento de Android 11.', 'articulosThumb/tel.jpg', 'android, android 11, beta, beta android, google, telefonos, telefonos, smartphones, celulares, celular, smartphone, tecnologia, reviews, review, 11, sistema operativo, so', NULL, 8, NULL, '2020-09-05 21:56:18'),
('AR09', 'ARTICULO 5G', 'Articulos/articulo%205g.html', 'Mayor velocidad y esperamos, menos uso de energia.', 'articulosThumb/5g.jpg', 'android, ios, beta, comunicaciones, google, telefonos, telefonos, smartphones, celulares, celular, smartphone, tecnologia, red, red celular, 4g, sistema 5g, 5g', NULL, 9, NULL, '2020-09-05 21:56:18'),
('AR10', 'ARTICULO Xbox Versus PS5', 'Articulos/articuloxboxps5.html', 'La presentacion de las especificaciones de la PlayStation 5.', 'Articulos/xbox%20ps5%203.png', 'juegos, gaming, consolas, consola, sony, microsoft, xbox, ps, playstation, xbox x, pc, gamers, gaming, videojuegos, estrenos, amd, review, reviews', NULL, 10, NULL, '2020-09-05 21:56:18'),
('AR11', 'ARTICULO Juegos gratis y lanzamientos', 'Articulos/articulosJuegoslunes30.html', 'Un repaso de los videojuegos que están por llegar, estrenos y regalos.', 'Articulos/hlalyx.jpg', 'juegos, telefonos, smartphone, xbox, ps, playstation, xbox x, pc, computadoras, gamers, gaming, videojuegos, estrenos, steam, half life, alyx, valve, ubisoft', NULL, 11, NULL, '2020-09-05 21:56:18'),
('AR12', 'Mario Bros Cumple 35 años', 'Articulos/articuloNintendo.html', 'El clasico videojuego de nintendo cumple su aniversario numero 35 en septiembre', 'Articulos/mario.jpg', 'videojuegos, juegos, nintendo, mario, mario bros, mario brothers, gaming, gamers, consolas, nintendo 64, pc, zelda', NULL, 12, NULL, '2020-09-05 21:56:18'),
('AR13', 'Mejoras en Whatsapp, juegos gratis y mas', 'Articulos/articulomoviles31-3.html', 'Te contamos las ultimas novedades para Whatsapp, te acercamos juegos gratis para android y tambien la verdad en las denuncias a Zoom.', 'Articulos/smartphones.jpg', 'Celulares, smartphones, whatsapp, facebook, zoom, juegos, videojuegos, tablets, telefonos, celular, internet, moviles, actualizadad, privacidad, datos, datos privados, informacion, denuncia', NULL, 13, NULL, '2020-09-05 21:56:18'),
('AR14', 'Hacker roba datos a Amd y Microsoft', 'Articulos/articuloHackerAmd.html', 'Un hacker logro robar datos de la nueva tarjeta grafica Amd para la Xbox X', 'Articulos/amdmicrosof.jpg', 'Amd, Microsoft, Hackers, Xbox, Xbox serie x, xbox x, consolas, consola, hackers, hackeo, programacion, codigos, robo de datos, hackeo', '31-3-2020', 14, NULL, '2020-09-05 21:56:18'),
('AR15', 'Posible Precio de la PS5, Keanu Reeves, y mas', 'Articulos/noticiasVarias1-4.html', 'Se filtro el posible precio de la nueva consola de Sony, la cual saldra al mercado este año, y la posibilidad de la llegada del actor canadiense a Marvel', 'Articulos/ps5precio.jpg', 'Marvel, ps5, playstation, amd, ps, consolas, console, gaming, Keanu Reeves, Ghost Rider, UCM, superheroes, comics, precio, actor', '1-4-20', 15, NULL, '2020-09-05 21:56:18'),
('AR16', 'Google Play permitira ver peliculas gratis', 'Articulos/noticiasGoogle2-4.html', 'El servicio de streaming de Google, ofrecera una gran cantidad de titulos de forma gratuita, con publicidad durante la cuarentena.', 'Articulos/googleplaymovies.jpg', 'Google, google play, ofertas, gratis, noticias, movies, peliculas, series, streaming, cuarentena, entretenimiento, ver peliculas gratis', '2-4-20', 16, NULL, '2020-09-05 21:56:18'),
('AR17', 'Grave problema en la seguridad de Windows', 'Articulos/Articulos/noticiasGoogle2-4.html', 'Han alertado que el sistema operativo en varias de sus versiones, desde la versión 7 en adelante, tiene un error grave en su seguridad.', 'Articulos/windNoti.jpg', 'Windows, microsoft, noticias, seguridad, informatica, seguridad, bugs, programacion, developers, windows 7, windows 10, hackers, hackeo', '2-4-20', 17, NULL, '2020-09-05 21:56:18'),
('AR18', 'Nuevo Iphone SE 2 en las proximas horas', 'Articulos/articuloIphone.html', 'La empresa de tecnologia anunciara pronto un nuevo telefono de gama media', 'Articulos/nuevoiphonese2.jpg', 'Apple, smartphones, telefonos, celulares, telefonia, anuncio, gama alta, gama media, iphone x, iphone se, iphone 9', '3-4-2020', 18, NULL, '2020-09-05 21:56:18'),
('AR19', '7 Juegos gratis en Steam', 'Articulos/articuloJuegos3-4.html', 'La plataforma de videojuegos regala por tiempo limitado 7 titulos mas', 'Articulos/steam.jpg', 'steam, juegos, videojuegos, gaming, gamers, games, ubisoft, indie, regalos, ofertas, pc, computadoras, informatica, gratis', '3-4-2020', 19, NULL, '2020-09-05 21:56:18'),
('AR20', 'Bill Gates invierte en fabricar 7 vacunas', 'Articulos/articuloBillgates.php', 'El dueño de Microsoft esta invirtiendo en fabricar vacunas contra el Coronavirus', 'Articulos/billGates.jpg', 'Microsoft, Bill gates, informatica, desarrollo, creacion, vacunas, enfermedades, coronavirus, covid19, hardware, fabricas', '4-4-2020', 20, NULL, '2020-09-05 21:56:18'),
('AR21', 'Centros de ayuda en Buenos Aires', 'Articulos/articuloCentrosayuda.html', 'Damos a conocer un listado otorgado por la Ciudad de buenos Aires de centros de asistencia', 'Articulos/bsas.jpg', 'Buenos aires, ayuda, coronavirus, covid-19, enfermedades, centros de ayuda, necesitados, asistencia, carenciados', '2-4-2020', 21, NULL, '2020-09-05 21:56:18'),
('AR22', 'Noticias de videojuegos', 'Articulos/articuloJuegos4-4.php', 'Amanzon se introduce a la industria de los videojuegos, Demo de Final Fantasy VII Y mas', 'Articulos/final4-4.jpg', 'Videojuegos, final fantasy vii, amazon, e3, eventos, consolas, stadia, google, cosola videogames square enix microsoft', '4-4-2020', 22, NULL, '2020-09-05 21:56:18'),
('AR23', 'Ofertas en la tienda de Nintendo', 'Articulos/articuloSwitch.html', 'Nintendo anuncio rebajas en su tienda electrónica a una gran cantidad de títulos y pronto se sumaran mas', 'Articulos/ninSwitch.jpg', 'Videojuegos, nintendo zelda ofertas breath of the wild ofertas rebajas juegos gratis consolas games gaming console gaming', '3-4-2020', 23, NULL, '2020-09-05 21:56:18'),
('AR24', 'Enterate de lo ultimo en videojuegos', 'Articulos/articuloJuegos4-4.php', 'Nuevo trailer del Remake del Final Fantasy VII y lo ultimo en videojuegos', 'Articulos/final4-4.jpg', 'videojuegos, switch nintendo juegos gaming gamers amazon crucible final fantasy vii Project Tempo stadia google square enix e3 steam gratis', '5-4-2020', 24, NULL, '2020-09-05 21:56:18'),
('AR25', 'Bill Gates invierte millones en 7 vacunas', 'Articulos/articuloBillgates.php', 'El dueño de Microsoft, invierte dinero en la construcción de fabricas, para el desarrollo de vacunas', 'Articulos/billGates.jpg', 'bill gates microsoft vacunas covid-19 coronavirus enfermades pandemia mellinda fundacion', '5-4-2020', 25, NULL, '2020-09-05 21:56:18'),
('AR26', 'Opinión: ¿Qué antivirus es mejor?', 'Articulos/articuloAntivirus.php', 'Los mejores antivirus para protejer tu dispositivo contra las amenazas informaticas existentes', 'Articulos/antivirus2.jpg', 'antivirus avg informatica software ccleaner avast nod32 libre gratis seguridad informatica vpn firewall malware', '6-4-2020', 26, NULL, '2020-09-05 21:56:18'),
('AR27', 'Noticias Generales 6 de Abril', 'Articulos/articuloNoticias6-4.php', 'Microsoft Edge desplaza a Firefox, la polemica del 5G en Inglaterra y mas', 'Articulos/edgeThumb.jpg', 'microsoft edge firefox navegadores google chrome 5g anti 5g 4k avances tecnologia internet explorer', '7-4-2020', 27, NULL, '2020-09-05 21:56:18'),
('AR28', 'Curso Programacion orientada a Objetos', 'Articulos/cursoPoo2.php', 'Continuamos con el curso de programacion orientado a objetos, viendo Java y su instalacion', 'Articulos/codigo1.jpg', 'java C# php clases objetos eclipse jdk instalacion poo curso gratis programacion', '7-4-2020', 28, NULL, '2020-09-05 21:56:18'),
('AR29', 'Una vacuna contra el Covid-19 entra en prueba', 'Articulos/articulo7-4.php', 'Una farmacéutica comenzara esta semana a realizar pruebas en personas en los Estados Unidos', 'Articulos/imgVacuna.jpg', 'covid-19 coronavirus vacunas bill gates microsoft melinda fundacion inversion salud pandemia', '7-4-2020', 29, NULL, '2020-09-05 21:56:18'),
('AR30', 'Google Arts and Culture', 'Articulos/articuloGoogleArts.php', 'Si te gusta pasear por los museos famosos, visitar lugares historicos, o aprender sobre historia esta aplicacion es para vos', 'Articulos/capturasGoogleArts/googleArts1.png', 'Historia museos aplicaciones google arts culture cultura arte app personajes historicos historia entretenimiento', '7-4-2020', 30, NULL, '2020-09-05 21:56:18'),
('AR31', 'Sony anuncia su control para Playstation 5', 'Articulos/articuloControles.php', 'Sony anuncia \"DualSense\", el sucesor de Dualshock 4, el control que acompaña la Playstation 5', 'Articulos/controlps5b.jpg', 'sony xbox serie x microsoft playstation 5 play 5 dualsense dualshock wireless controller xbox one playstation 4 consolas videojuegos gaming gamers', '8-4-2020', 31, NULL, '2020-09-05 21:56:18'),
('AR32', 'Tesla y Foxconn, productores de respiradores', 'Articulos/articulo8-4.php', 'La empresa socia de Apple, comunico su acuerdo con empresas de la salud para crear equipo medico.', 'Articulos/respiradores.png', 'apple foxconn tesla respiradores covid elon musk autos electricos windows 10 microsoft w10 errores bugs pantalla azul', '8-4-2020', 32, NULL, '2020-09-05 21:56:18'),
('AR33', '¡Videojuegos en oferta!', 'Articulos/articulo9-4.php', 'Hoy te traemos una lista de los videojuegos en oferta para disfrutar, y poder sobrellevar la cuarentena un poco mejor. ', 'Articulos/stadia.jpg', 'google stadia juegos ps4 playstation videojuegos pc steam android counter strike cs 1.6 rebajas ofertas capcom resident evil fifa', '9-4-2020', 33, NULL, '2020-09-05 21:56:18'),
('AR34', 'Final Fantasy a la venta, Cyberpunk y más', 'Articulos/articulo10-4.php', 'Uno de los remakes más esperados este año, ya se encuentra a la venta, ademas lo ultimo sobre Cyberpunk 2077 entre otras cosas.', 'Articulos/cpxbox.jpg', 'ps4 ps5 juegos cyberpunk final fantasy vii remake playstation videojuegos pc square enix rebajas ofertas twitter huawei xbox serie x xbox one', '10-4-2020', 34, NULL, '2020-09-05 21:56:18'),
('AR35', 'Más de 60 cursos gratis - Universidad de Harvard', 'Articulos/articulo11-4.php', 'La Universidad esta ofreciendo de forma online y gratuita, cursos de capacitación en distintos temas y áreas.', 'Articulos/harvard.png', 'programacion harvard universidad estudiar informatica estudios cursos gratis capacitacion internet web redes humanidades noticias generales', '11-4-2020', 35, NULL, '2020-09-05 21:56:18'),
('AR36', 'Los mejores sitios para aprender a programar', 'Articulos/articuloPaginasAprenderCodigo.php', 'Te acercamos una lista de sitios, canales de youtube y otros lugares, para que puedas aprender o consultar dudas', 'Articulos/codigo1.jpg', 'desarrollo web estudiar cursos gratis w3schools programar programacion datos informatica java sql python php c c++ c# html5 css3 javascript desarrollo de videojuegos ', '11-4-2020', 36, NULL, '2020-09-05 21:56:18'),
('AR37', 'Como evitar pagar de mas en telefonia', 'Articulos/articulo12-4.php', 'Es importante revisar lo que pagamos por los servicios de comunicación. Últimamente algunos servicios aumentan sus planes de pago sin avisar', 'Articulos/telefono1.jpg', 'smartphone 5g telefonia movil celulares internet redes promociones empresas ahorrar', '12-4-2020', 37, NULL, '2020-09-05 21:56:18'),
('AR38', 'Las últimas noticias en videojuegos', 'Articulos/articulo13-4.php', 'Un nuevo Resident Evil en camino y rumores sobre su contenido. También podes leer como Valve está trabajando en un nuevo Half Life', 'Articulos/re8.jpg', 'juegos, videojuegos, resident evil 8 resident evil 4 capcom valve steam remakes half life alyx half life 3 gaming gamers pc gaming', '13-4-2020', 38, NULL, '2020-09-05 21:56:18'),
('AR39', 'Noticias de Marvel ¿Regresa Tony Stark? ¡Comics libres!', 'Articulos/articulo13-4bis.php', 'Se filtró parte del guion de Thor: Love And Thunder, y ¿el regreso de Tony Stark? Además te contamos como leer comics gratis', 'Articulos/tonystark.jpg', 'comics gratis marvel peliculas historietas tony stark iron man thor: love and thunder black widow scarlet jhohansen avengers vengadores', '13-4-2020', 39, NULL, '2020-09-05 21:56:18'),
('AR40', 'Mejoras a Instagram, y nuevos teléfonos de Samsung', 'Articulos/articulo14-4.php', 'Samsung lanzó al mercado 5 nuevos teléfonos, entre ellos, dos de los nuevos terminales tienen la opción para 5G.', 'Articulos/sama51.jpg', 'samsung a51 a71 a21 a11 a01 5g noticias smartphone telefonos telefonia movil moviles instagram mejoras telefonos economicos', '14-4-2020', 40, NULL, '2020-09-05 21:56:18'),
('AR41', 'Noticias de videojuegos de Abril', 'Articulos/articulo15-4.php', 'Crecen los rumores de un nuevo remake de Capcom. Sony: Play at Home y juegos argentinos', 'Articulos/resident4.jpg', 'resident evil 4 resident evil 8 capcom remake juegos argentinos juegos gratis ofertas sony ps4 playstation 4 juegos argentinos desarrollo gaming gamers pc xbox', '15-4-2020', 41, NULL, '2020-09-05 21:56:18'),
('AR42', 'Según Bill Gates, podrían pasar 18 hasta que volvamos a la normalidad', 'Articulos/articulo17-4.php', 'En un programa de la BBC, el millonario que lleva algunos años advirtiendo sobre una posible crisis sanitaria, explico que una vacuna podría poner fin a esta situación', 'Articulos/billGates.jpg', 'microsoft windows virus covid-19 coronavirus vacuna informacion bill gates melinda gates empresas salud opinion', '17-4-2020', 42, NULL, '2020-09-05 21:56:18'),
('AR43', '¡Juegos gratis de esta semana!', 'Articulos/articulo16-4.php', 'La Epic Games Store regala los juegos Just Cause 4 y Wheels of Aurelia, ademas se confirmo el remake del mitico juego Crysis', 'Articulos/Cyberpunk-2077.jpg', 'juegos gratis epic games steam cyberpunk xbox serie x xbox one controles joystick gaming gamers pc gaming keanu reeves crytek', '16-4-2020', 43, NULL, '2020-09-05 21:56:18'),
('AR44', 'Programacion Orientada a Objetos, clase 6', 'Articulos/cursoPoo6.php', 'Continuamos con el curso de POO, viendo los metodos y clases de la api de Java, y veremos los distintos operadores de los que disponemos.', 'Articulos/programacionCursoPOO.jpg', 'cursos curso gratis java curso c# curso php poo programacion orientada a objetos desarrollo curso programacion developers programming', '18-4-2020', 44, NULL, '2020-09-05 21:56:18'),
('AR45', 'Es hora de mira a oriente, artículo de opinión.', 'Articulos/articuloOpinion18-4.php', 'Artículo de opinión de uno de nuestros redactores, sobre la situación en el mundo y la forma en que los lideres mundiales enfrentaron la crisis mundial.', 'Articulos/artOpinion.jpg', 'covid-19 covid 19 coronavirus china honk kong taiwan enfermedades medios de comunicacion censura', '18-4-2020', 45, NULL, '2020-09-05 21:56:18'),
('AR46', 'Google anuncio que aumentó la cantidad de estafas online', 'Articulos/articulo19-4.php', 'Del total de correos electrónicos que se denunciaron por ser fraude o phishing, utilizan la temática “pandemia”, “coronavirus”, “covid” o palabras relacionadas con ello.', 'Articulos/gseguri.png', 'covid-19 covid 19 coronavirus google estafas phishing hackeos hackers fraudes scammers scamming google gmail', '19-4-2020', 46, NULL, '2020-09-05 21:56:18'),
('AR47', 'Apple apuesta por un dispositivo económico', 'Articulos/articulo20-4.php', 'La nueva generación de Iphone SE sale al mercado, este 24 de abril y costara en su versión más económica 400 dólares, unos 26 mil pesos en la Argentina actualmente.', 'Articulos/iphoneSE.jpg', 'apple samsung apple se 2 smartphones telefonos telefonia gama alta telefonia iphone se 2 iphone 9 samsung edge samsung flip z', '20-4-2020', 47, NULL, '2020-09-05 21:56:18'),
('AR48', 'Ofertas de videojuegos por pocas horas', 'Articulos/articulo20-4bis.php', 'Te contamos de estas ofertas rápidas, de las que tenes que aprovechar en las próximas horas porque se irán rápido.', 'Articulos/steam.jpg', 'ofertas steam ofertas videojuegos gaming juegos gratis rebajas videogames gamers ofertas en pc', '20-4-2020', 48, NULL, '2020-09-05 21:56:18'),
('AR49', 'Ofertas de videojuegos para todas las plataformas', 'Articulos/articulo21-4bis.php', 'En esta ocasión, no te traemos juegos solo para una plataforma o para algunas, sino para las 6 plataformas más populares del momento.', 'Articulos/gaming.jpg', 'ofertas steam ofertas videojuegos gaming juegos gratis rebajas videogames gamers ofertas en pc google stadia xbox x xbox one xbox scarlet playstation 4 ps 4 ps 5 nintendo switch ofertas en consolas epic store ubisoft', '21-4-2020', 49, NULL, '2020-09-05 21:56:18'),
('AR50', 'La fundación Gates y La Oms habrían sufrido un ataque informático', 'Articulos/articulo22-4.php', 'Comenzó a circular por distintos sitios de internet la información sobre cuentas de correo electrónico, usuarios y contraseñas de más de 25 mil personas relacionadas con estas empresas.', 'Articulos/hackeo.jpg', 'hackeo microsoft hackeo oms bn banco mundial hackers crackeo datos informacion hackeo a fundacion gates hackeo a bill gates anti 5g anti aislamiento social', '22-4-2020', 50, NULL, '2020-09-05 21:56:18'),
('AR51', 'Youtube demandada, Netflix y Zoom en crecimiento y noticias de Facebook', 'Articulos/articulo23-4.php', 'A pesar de las denuncias y quejas contra la plataforma de video llamadas, zoom sigue sumando seguidores y prometiendo parches y opciones de seguridad.', 'Articulos/yotubeAlt.jpg', 'youtube netflix zoom seguridad informatica encriptacion criptomonedas ripple facebook cuentas falsas phishing fake news', '23-4-2020', 51, NULL, '2020-09-05 21:56:18'),
('AR52', 'Usuarios de Nintendo Switch reportaron ingresos no autorizados a sus cuentas', 'Articulos/articulo24-4.php', 'En los últimos días, se ha reportado a muchos usuarios de la última consola de Nintendo, denunciando ingresos a su cuenta no autorizados y que incluso se realizaron compras sin permiso.', 'Articulos/ninSwitch.jpg', 'nintendo switch consolas estafas hackeos robo de cuentas juegos lanzamientos nintendo bioshock 2k borderlands xenoblade: chronicles', '24-4-2020', 52, NULL, '2020-09-05 21:56:18'),
('AR53', 'Mick Jagger y los Rolling Stones, con mucha actividad en abril', 'Articulos/articulo24-4bis.php', 'Pese a que todo el mundo parece detenido por la crisis del corona virus, la banda británica, y sobre todo su cantante parecen mantenerse más activos que nunca durante este mes.', 'Articulos/mickJ.jpg', 'paul mccartney mick jagger keith richards los rolling stones musica conciertos live conviertos virtuales streaming', '24-4-2020', 53, NULL, '2020-09-05 21:56:18'),
('AR54', 'Apple rompe su sociedad con Intel', 'Articulos/articulo25-4.php', 'La empresa cofundada por Steve Jobs, confirmó en los últimos días uno de los rumores que venían resonando con fuerza.', 'Articulos/mac.jpg', 'apple microprocesadores intel amd microchips empresas componentes de pc hardware msi asus placas pci', '25-4-2020', 54, NULL, '2020-09-05 21:56:18'),
('AR55', 'Nueva rivalidad para Zoom: Messenger Rooms', 'Articulos/articulo25-4bis.php', 'Entre la polémica por sus fallas de seguridad, empresas que la prohíben, otras que la siguen usando como su única opción, Facebook presentó Messenger Rooms.', 'Articulos/mssengerRooms.jpg', 'facebook seguridad informatica hackeos crackeos datos messenger rooms zoom microsoft teams robo de cuentas robo de datos web hacking', '26-4-2020', 55, NULL, '2020-09-05 21:56:18'),
('AR56', 'Nintendo confirmó el robo de cuentas', 'Articulos/articulo26-4.php', 'La empresa productora de la consola portátil Switch, confirmó en los últimos días una noticia que circulaba por las redes y medios, dueños de esta consola sufrieron accesos no autorizados a sus cuentas de forma remota, e incluso compras desde sus cuentas.', 'Articulos/switch1.jpg', 'nintendo switch seguridad informatica hackeos crackeos datos robo de cuentas robo de datos web hacking juegos en oferta estrenos', '26-4-2020', 56, NULL, '2020-09-05 21:56:18'),
('AR57', 'Kristofer Hivyu, conocido por su papel de Tormund en GOT, se une a The Witcher', 'Articulos/articulo28-4.php', 'Ya recuperado de su contagio por Covid-19, el actor vuelve a ser noticia, esta vez por algo bueno. Parece que al noruego de 41 años la vida no le da descansos, una buena y una mala.', 'Articulos/thewitcher.jpg', 'GOT game of thrones tormund the witcher netflix series Kristofer Hivyu star wars episodio 9 peliculas disney', '28-4-2020', 57, NULL, '2020-09-05 21:56:18'),
('AR58', 'Ubuntu Linux lanzó su versión 20.04 LTS', 'Articulos/articulo28-4bis.php', 'La distribución LTS, Long Term Support o Soporte de largo término, del sistema operativo Ubuntu se anunció este 23 de abril.', 'Articulos/fondoUbuntu.jpg', 'ubuntu, software open source so sistemas operativos linux mejoras desarrollo programacion lanzamiento novedades noticias', '28-4-2020', 58, NULL, '2020-09-05 21:56:18'),
('AR59', 'Google Meet gratuito desde el 4 de mayo, y límite en el reenvío de cadenas y virales de Whatsapp', 'Articulos/articulo29-4.php', 'Desde el 7 de abril, los mensajes virales tienen un límite para ser enviados, con el fin de frenar la desinformación. A partir de esa actualización, los mensajes solo se pueden reenviar una vez por chat.', 'Articulos/googleMeet.jpg', 'whatsapp mensajes informacion datos virales google meet gratis gratuito noticias estafas ', '25/05/20', 59, NULL, '2020-09-05 21:56:18'),
('AR60', 'Riot lanzó la versión móvil de Legends of Runaterra y Epic Games su autenticador en dos pasos', 'Articulos/articulo29-4bis.php', 'La empresa de videojuegos anunció que la versión para dispositivos móviles del juego de cartas, basado en la historia y temática de League of Legends, ya está disponible en su versión 1.0 para Android y iOS, de forma gratuita.', 'Articulos/legends.png', 'riot games lol league of legends epic games juegos gratis legends of runaterra gaming pc videojuegos pc fornite', '25/05/20', 60, NULL, '2020-09-05 21:56:18'),
('AR61', 'Ubisoft mostró el tráiler del nuevo Assassin’s Creed', 'Articulos/articulo30-4.php', 'La nueva entrega, que se titulará Valhalla, estará ambientando en las guerras de los vikingos, con una temática completamente nórdica y protagonizado por Eivor, una leyenda vikinga.', 'Articulos/assassins.jpg', 'ubisoft assassins creed valhala videojuegos gaming pc juegos gratis noticias consolas ubistore uplay', '25/05/20', 61, NULL, '2020-09-05 21:56:18'),
('AR62', '¿La cuarentena no le cae bien a Elon Musk?', 'Articulos/articulo1-5.php', 'Elon viene llevando una cuarentena errática, como una montaña rusa, con altos y bajos. Comenzó con opiniones polémicas, diciendo que la pandemia no afectaría como se esperaba...', 'Articulos/elon-musk-coronavirus.jpg', 'elon musk tesla spacex cuarentena covid-19 corona virus informacion empresas finanzas ingenieria opinion facebook mark zuckerberg', '25/05/20', 62, NULL, '2020-09-05 21:56:18'),
('AR63', 'Programacion Orientada a Objetos, clase 7', 'Articulos/cursoPoo7.php', 'Continuamos con el curso de POO, viendo como pedir y almacenar datos del usuario, mostrando mensajes que solicitan información para quien maneja el programa, y permitirle introducir datos por el teclado.', 'Articulos/programacionCursoPOO.jpg', 'java poo programacion orientada a objetos curso gratis de programacion informatica datos curso gratuito de java', '25/05/20', 63, NULL, '2020-09-05 21:56:18'),
('AR64', 'Assassins Creed 2 gratis. Además, nuevas placas Aorus para los Intel de décima generación', 'Articulos/articulo3-5.php', 'Assassins Creed II, uno de los juegos más aclamados de la saga, se encuentra gratis en la plataforma Uplay, desde su store.', 'Articulos/giggabyte.jpg', 'uplay ubisoft assassins creed II gratis assassins creed valhala placas base gaming gigabyte intel amd hardware informatica computacion gaming', '25/05/20', 64, NULL, '2020-09-05 21:56:18'),
('AR65', '¿Qué hacer ante las estafas de la pandemia?', 'Articulos/articulo4-5.php', 'Las personas que se dedican a delinquir en internet aprovechan las oportunidades diarias con que se topan, para robar información, vulnerar sistemas web y estafar a personas comunes y corrientes, por mencionar solo algunos delitos conocidos.', 'Articulos/TRABAJOSANTI.jpg', 'seguridad informatica consejos antivirus phishin estafas hackers hackeo crackers fraudes online malware virus informaticos troyanos crackeo', '25/05/20', 65, NULL, '2020-09-05 21:56:18'),
('AR66', 'Noticias del universo Star Wars', 'Articulos/articulo5-5.php', 'Ayer, el día conocido como May the Forth Be With You, fecha que los fanáticos de la saga bautizaron como el día de Star Wars, fue el elegido por Disney para llevar a su plataforma de streaming la última película del universo cinematográfico.', 'Articulos/starwars.jpg', 'star wars series peliculas the rise of the skywalker the mandalorian disney + El Ascenso de Skywalker star wars day may the 4', '25/05/20', 66, NULL, '2020-09-05 21:56:18'),
('AR67', 'La eterna lucha AMD vs Intel, y los nuevos competidores', 'Articulos/articulo5-5bis.php', 'Desde hace ya años, las dos empresas se han caracterizado por participar en una competencia en formato duopolio, intentando ver cual lidera en términos de potencia bruta y rendimiento.', 'Articulos/amdmicrosof.jpg', 'amd intel apple qualcomm snapdragon procesadores hardware informatica computacion noticias competencia ryzen i3 i5 i7 i9 placas base microchips', '25/05/20', 67, NULL, '2020-09-05 21:56:18'),
('AR68', 'Microsoft anunció desde la Xbox Insider los juegos para su nueva consola', 'Articulos/articulo9-5.php', 'Cada trabajador en su propia casa, pero aun asi Microsoft logró presentar oficialmente su nueva consola y los juegos que se optimizarán en su salida, para poder disfrutarlos con toda la tecnología nueva que trae.', 'Articulos/xboxx.jpg', 'amd microsoft xbox serie x xbox one juegos raytraicing rtx nvidea navi vega intel ps playstation xbox 360 Xbox Insider Cyberpunk 2077 Assassins Creed Valhalla', '25/05/20', 68, NULL, '2020-09-05 21:56:18'),
('AR69', 'IBM lanza su plataforma de E-Learning en español', 'Articulos/articulo11-5.php', 'IBM en esta ocasión, se puso manos a la obra y decidió anunciar Open P-TECH, una plataforma de E-Learning gratuita.', 'Articulos/codigo1.jpg', 'imb elearning cursos online gratuitos en español certificacion programacion seguridad informatica big data machine learning cloud computer', '25/05/20', 69, NULL, '2020-09-05 21:56:18'),
('AR70', 'Los juegos anunciados para la Playstation 5', 'Articulos/articulo13-5.php', 'Hoy, te traemos algunos de los juegos anunciados para la consola de Sony, que tiene fecha de salida similar a la de Microsoft, diciembre de este año, y que ya confirmo a varios de sus títulos clásicos y exclusivos.', 'Articulos/controlps5a.jpg', 'microsoft amd intel nvidea navi vega ryzen playstation 5 sony ps4 ps5 juegos gaming consolas console gamers nuevas consolas', '25/05/20', 70, NULL, '2020-09-05 21:56:18'),
('AR71', 'Epic Games, ofrece GTA V gratis hasta el 21 de mayo', 'Articulos/articulo15-5.php', 'Este jueves, la Store se mantuvo gran parte del día offline o con problemas para acceder, debido a la noticia del juego gratis de la semana: GTA V.', 'Articulos/gta-v.jpg', 'rockstar games gta iv gta v gratis epic games juegos gratis gaming pc consolas steam plataformas de videojuegos noticias de videojuegos', '25/05/20', 71, NULL, '2020-09-05 21:56:18'),
('AR72', 'La seguridad en tiempos del teletrabajo', 'Articulos/articulo18-5.php', 'Las consultas que el sitio y sus afiliados más reciben en los últimos meses tratan sobre la seguridad informática, los ciberataques y como prevenir o solucionar problemas de esta índole. ', 'Articulos/hackeo.jpg', 'zoom ciberseguridad datos hackers hackeo informatica programacion desarrollo web ', '25/05/20', 72, NULL, '2020-09-05 21:56:18'),
('AR73', 'La décima generación de Intel ya esta con nosotros', 'Articulos/articulo20-5.php', 'Hoy veremos una pequeña reseña de los nuevos procesadores de Intel, intentando que puedas conocer todo lo necesario para que, si decidís actualizar tu computadora por un procesador de estas características, estés informado en todos sus aspectos.', 'Articulos/intel02.jpg', 'procesadores intel decima generacion amd i7 10700l i9 10900k procesadores placas base hardware informatica reviews informacion socket 1200', '25/05/20', 73, NULL, '2020-09-05 21:56:18'),
('AR74', 'Mejores antivirus - Artículo de opinión (Actualizado)', 'Articulos/articulo21-5.php', 'Existen muchas opciones entre los antivirus en el mercado, Después de haber trabajado varios años con distintos antivirus, siempre recibimos la pregunta, ¿Qué antivirus es mejor? ¿Cuál me conviene más?', 'Articulos/antivirus2.jpg', 'antivirus seguridad informatica antimalware virus troyanos avg avast panta norton computacion software programacion desarrollo hackers hackeo crackers ', '25/05/20', 74, NULL, '2020-09-05 21:56:18'),
('AR75', 'Septiembre sería el mes indicado por AMD para nuevos lanzamientos', 'Articulos/articulo22-5bis.php', 'Es que según los rumores, la empresa esta lista para que en esa fecha sean anunciados y salgan al mercado los procesadores Ryzen 4000, la cuarta generación de procesadores de Ryzen, junto con las placas base 550X y 520', 'Articulos/amdmicrosof.jpg', 'amd intel procesadores hardware informatica computacion noticias competencia ryzen 4 cuarta generacion amd ryzen placas base 520 55', '25/05/20', 75, NULL, '2020-09-05 21:56:18'),
('AR76', 'Curso de Programación Orientada a Objetos', 'Articulos/cursoPoo8.php', 'Vamos a comenzar a realizar estas tareas, pero mediante otra clase, parte de un paquete de Java, llamado Swing, el cual nos permite crear programas con interfaces gráficas.', 'Articulos/programacionCursoPOO.jpg', 'java poo programacion orientada a objetos curso gratis de programacion informatica datos curso gratuito de java', '25/05/20', 76, NULL, '2020-09-05 21:56:18'),
('AR76', 'La organización Kaspersky denunció otro ciberataque', 'Articulos/articulo24-5.php', 'Parece que los hackers de guante negro y ladrones informáticos no tienen descanso durante la pandemia, los ataques a empresas, organismos gubernamentales y personas particulares no cesa, sino que cada dia se incrementa mas y mas.', 'Articulos/codigo1.jpg', 'seguridad informatica consejos antivirus phishin estafas hackers hackeo crackers fraudes online malware virus informaticos troyanos crackeo', '25/05/20', 77, NULL, '2020-09-05 21:56:18'),
('AR78', 'Noticias de AMD y el mundo de la informática', 'Articulos/articulo25-5.php', 'A la hora de elegir un procesador, y decantarse por un Intel o por un AMD, mucha gente suele oír a los expertos, y ver que elecciones toman las figuras mas importantes del sector de la informática', 'Articulos/amdSample.jpg', 'amd intel apple qualcomm snapdragon procesadores hardware informatica computacion noticias competencia ryzen threadripper 3950x linux ubuntu 20', '25/05/20', 78, NULL, '2020-09-05 21:56:18'),
('AR80', 'Noticias de videojuegos, 25 de mayo', 'Articulos/articulo25-5bis.php', 'Desde cuentas de twitter relacionadas con la plataforma, y desde diferentes sitios web de noticias, se han dado rumores sobre los próximos juegos de la competencia de Steam, Epic Games.', 'Articulos/gaming.jpg', 'gaming juegos juegos gratis noticias videojuegos steam ubisoft epic games civilization gta v valve ps4 ps5 amd intel playstation ark the last of us ii', '25/5/2020', 79, NULL, '2020-09-05 21:56:18'),
('AR79', 'Llegan nuevos juegos exclusivos de Epic Games a Steam', 'Articulos/articulo26-5.php', 'Tres nuevos títulos, los cuales fueron muy bien recibidos durante su salida, llegarán a la plataforma de videojuegos de Valve, se trata de Heavy Rain, Beyond Two Souls y Detroit: Become Human.', 'Articulos/beyondts.jpeg', 'gaming juegos juegos gratis noticias videojuegos steam ubisoft epic games civilization gta v valve ps4 ps5 amd intel playstation ark the last of us ii heavy rain beyond two souls', '26/5/2020', 80, NULL, '2020-09-05 21:56:18'),
('AR81', 'SpaceX Lanza mañana su primer misión tripulada', 'Articulos/articulo26-5bis.php', 'El administrador de la NASA, Jim Bridenstine, anunció que mañana, miercoles 27 de mayo, será el día del lanzamiento del Crew Dragon, la nave creada por la empresa subsidiaria de Elon Musk', 'Articulos/spacex.jpg', 'exploracion espacial elon musk spacex nasa dragon crew espacio exterior iss astronautas tecnologia noticias cohetes mision tripulada', '26/5/2020', 81, NULL, '2020-09-05 21:56:18'),
('AR82', 'Dead By Deadlight tendrá a Pyramid Head en forma de DLC, además, Blizzard cancela la Blizzcon', 'Articulos/articulo27-5.php', 'El juego multijugador de supervivientes y asesinos, en colaboración con Konami, lanzará en junio un DLC que contendrá al clásico personaje de Silent Hill, el asesino Pyramid Head, para jugar', 'silenthill.jpg', 'dlc juegos sillent hill dead by deadlight videojuegos juegos gratis ofertas informacion juegos xbox pc ps playstation blizzard blizzcon', '27/05/2020', 82, NULL, '2020-09-05 21:56:18'),
('AR83', 'Donald Trump VS las redes sociales', 'Articulos/articulo29-5.php', 'El día de ayer, el presidente de los Estados Unidos firmó un decreto por el cual las redes sociales como Twitter, Facebook y similares, deberán hacerse cargo del contenido que sus usuarios publican como noticias.', 'Articulos/dtrump.jpg', 'seguridad informatica consejos antivirus estafas fake news crackeo donald trump mark zuckerberg polemica estados unidos redes sociales facebook twitter', '01/06/20', 83, NULL, '2020-09-05 21:56:18'),
('AR84', 'En medio de las protestas en Estados Unidos, un periodista de la CNN fue arrestado en vivo', 'Articulos/articulo29-5bis.php', 'En ese momento, un periodista de la CNN, Omar Jiménez, transmitía en vivo los hechos, junto a su equipo, cuando la policía lo arresto en vivo.', 'Articulos/omarj.png', 'cnn donald trump protestas informacion periodismo independiente redes protestas omar jimenez george floyd', '29/05/2020', 84, NULL, '2020-09-05 21:56:18'),
('AR85', 'Liberan a equipo de CNN que fue arrestado', 'Articulos/articulo29-5bis-actualizacion.php', 'Luego de algunas horas, el equipo arrestado fue liberado de las instalaciones de Seguridad Pública del Condado de Hennepin en el centro de Minneapolis, en los Estados Unidos.', 'Articulos/omarjliberado.jpg', 'cnn donald trump protestas informacion periodismo independiente redes protestas omar jimenez george floyd periodistas protestas riots disturbios en estados unidos', '29/05/2020', 85, NULL, '2020-09-05 21:56:18'),
('AR86', 'Xiaomi lanza sus laptops con procesadores Ryzen', 'Articulos/articulo30-5.php', 'En los últimos días, la empresa China anunció que saldrán al mercado, sus nuevas computadoras portátiles, las cuales contarán con procesadores APU de AMD', 'Articulos/Xiaomi13.jpg', 'xiaomi celulares smartphones computadoras laptops notebooks amd intel zen2 zen3 apu ryzen 3 ryzen 5 ryzen 7 ryzen 4000 apu pc', '30/05/2020', 86, NULL, '2020-09-05 21:56:18'),
('AR87', 'Valorant muestra su tráiler de lanzamiento oficial', 'Articulos/articulo30-5bis.php', 'El último juego de Riot Games, un shooter en primera persona, con lanzamiento oficial para este 2 de junio, mostró ayer a última hora un nuevo tráiler con contenido nuevo.', 'Articulos/riot.jpg', 'juegos games informatica pc valorant riot lol league of legends juegos gratis free to play noticias', '30/05/2020', 87, NULL, '2020-09-05 21:56:18'),
('AR88', 'Los astronautas del Crew Dragon llegaron a la estación espacial internacional', 'Articulos/articulo31-5.php', 'ELa misión tripulada por los astronautas Doug Hurley y Bob Behnken, finalmente lograron acoplarse a la estación ISS, hace algunas horas, luego de su lanzamiento.', 'Articulos/spacex.jpg', 'crew dragon noticias spacex exploracion espacial estacion espacial internacional iss eei astronautas elon musk nasa viaje espacial', '31/05/2020', 88, NULL, '2020-09-05 21:56:18'),
('AR89', 'En junio tendrá lugar el evento de Sony para Playstation 5', 'Articulos/articulo1-6.php', 'Sony tiene planeado para junio, mas específicamente para este jueves 4, un evento completamente en linea, vía un streaming al igual que la Microsoft Insider.', 'Articulos/controlps5b.jpg', 'juegos games playstation 5 ps 5 ps 4 playstation 4 sony videojuegos gaming pc xbox serie x microsoft evento ps insider', '01/06/2020', 89, NULL, '2020-09-05 21:56:18'),
('AR90', 'La situación política y social en Estados Unidos empeora', 'Articulos/articulo1-6bis.php', 'En medio de los disturbios y protestas por el crimen de George Flyod, la casa blanca vivió algo que jamas había pasado en la historia, apagó sus luces por completo y su presidente, Donald Trump, fue llevado con su familia al bunker presidencial.', 'Articulos/casablanca.jpg', 'donald trump controversia tweets twits twitter casa blanca disturbios en ee uu disturbios en estados unidos bunker presidencial noticias george floyd cnn', '01/06/2020', 90, NULL, '2020-09-05 21:56:18'),
('AR91', 'Anonymus reaparece tras el asesinato de George Floyd', 'Articulos/articulo1-6bis2.php', 'El grupo de hackers activistas reapareció en las redes tras publicar videos y realizar posteos en varias redes sociales y páginas, volviendo a ser tendencia.', 'Articulos/anonymus.jpg', 'donald trump controversia tweets twits twitter casa blanca disturbios en ee uu disturbios en estados unidos bunker presidencial noticias george floyd anonymus hackers cracker activistas', '01/06/2020', 91, NULL, '2020-09-05 21:56:18'),
('AR93', 'Juegos gratis, ofertas y noticias', 'Articulos/articulo2-6.php', 'Te traemos las ultimas noticias en videojuegos de la semana, Borderlands, Ark, Valorant, Battlefront II y mas', 'Articulos/gaming.jpg', 'riot games lol league of legends epic games juegos gratis legends of runaterra gaming pc videojuegos pc fornite battlefront II ea steam valorant lol gta V nintendo switch bioshock playstation Samurai Shodown NeoGeo', '02/06/20', 92, NULL, '2020-09-05 21:56:18'),
('AR94', 'Juegos gratis, ofertas y noticias', 'Articulos/articulo2-6.php', 'Epic Games está en este momento regalando en su plataforma de videojuegos, hasta el próximo jueves, Borderlands, como ya te contamos en noticias anteriores. Apenas termine esta oferta, podrás comenzar a reclamar para tu biblioteca, Ark Survival Evolved', 'Articulos/gaming.jpg', 'videojuegos gratis ofertas epic games borderlands Ark Survival Evolved steam Samurai Shodown Playstation Xbox One  Nintendo Switch Android Star Wars Battlefield 2 valorant riot games lol league of legends', '02/06/2020', 93, NULL, '2020-09-05 21:56:18'),
('AR95', 'Android retrasa su evento del 3 de junio', 'Articulos/articulo2-6bis.php', 'En este caso Google decidió cancelar por el momento un evento en el cual mostraría las noticias de su nuevo sistema operativo Android 11, dada la situación social y política actual en los Estados Unidos.', 'Articulos/android11logo.jpg', 'android desarrolladores programacion ois moviles telefonos celulares smartphones noticias de tecnologia android 11 beta abierta', '02/06/2020', 94, NULL, '2020-09-05 21:56:18'),
('AR96', 'Total War Troy, gratis en Epic Games', 'Articulos/articulo3-6.php', 'Otro juego mas que Epic Games suma a su lista de juegos que ha puesto en oferta para poder reclamarlo de forma gratuita en la biblioteca, y tenerlo permanentemente desde el 13 de agosto', 'Articulos/epicgames.png', 'juegos steam epic games valve videojuegos juegos gratis ofertas exclusivos informatica ps4 ps5 Total War Troy gaming', '03/06/2020', 95, NULL, '2020-09-05 21:56:18'),
('AR97', 'Evan Peters llega a Marvel', 'Articulos/articulo4-6.php', 'WandaVision es una de las próximas entregas del universo de Marvel, sobre la que se rumorea que, Evan Peters podria participar', 'Articulos/WandaVision.jpg', 'wanda vision marvel disney ciencia ficcion comics xmen fox quicksilver avengers peliculas evan peters', '04/06/2020', 96, NULL, '2020-09-05 21:56:18'),
('AR98', 'Nintendo lanza una nueva serie de ofertas', 'Articulos/articulo6-6.php', 'La plataforma de ventas de videojuegos de la empresa, ha decidido colocar en rebaja una gran cantidad de juegos en oferta. Más de 350 títulos, en realidad, con descuentos de hasta el 80% en algunos casos.', 'Articulos/ninSwitch.jpg', 'nintendo switch ofertas juegos gratis rebajas exclusivos gaming consolas valorant riot games playstation xbox serie x xbox 360 xbox one ps4 ps3 ps5 sony microsoft console gaming', '06/06/2020', 97, NULL, '2020-09-05 21:56:18'),
('AR99', 'Zoom no encriptará las llamadas de su servicio gratuito', 'Articulos/articulo7-6.php', 'La plataforma decidio que esta funcion solo sea disponible para usuarios pagos, te explicamos porque.', 'Articulos/hackeo.jpg', 'zoom privacidad seguridad informatica developers desarrolladores programacion hackers delitos informaticos ciberseguridad software computacion', '07/06/2020', 98, NULL, '2020-09-05 21:56:18'),
('AR100', 'Apple rastreara los dispositivos de los saqueos en Estados Unidos', 'Articulos/articulo7-6bis.php', 'La empresa aviso que sus dispositivos de muestra cuentan con un sistema de rastreo y ademas seran bloqueados.', 'Articulos/appleStore.jpg', 'apple privacidad seguridad informatica developers desarrolladores programacion hackers delitos informaticos ciberseguridad software computacion saqueos seguridad informatica iphone ipad mac pewdiepie donaciones george floyd saqueos protesta riots', '07/06/2020', 99, NULL, '2020-09-05 21:56:18'),
('AR101', 'Luego de la suspensión de su evento, Sony prepara una nueva presentación', 'Articulos/articulo8-6.php', 'Tras la situacion en los Estados Unidos, Sony decidio retrasar una semana su presentacion', 'Articulos/controlps5b.jpg', 'playstation 5 evento ps4 ps3 ps5 presentacion consolas gaming videojuegos informatica dualsense dualshock sony xbox streaming youtube twich', '08/06/2020', 100, NULL, '2020-09-05 21:56:18'),
('AR102', 'En fabricación los primeros teléfonos con cámara frontal oculta', 'Articulos/articulo9-6.php', 'Una empresa china comenzo a producir en masa los primeros telefonos con camara oculta bajo la pantalla', 'Articulos/visionox.jpg', 'smartphones telefonia camara oculta under display amoled oled visionox camara frontal bajo pantalla notch samsung iphone apple xiaomi oneplus motorola lg telefonos moviles desarrollo ingenieria computacion informatica', '09/06/2020', 101, NULL, '2020-09-05 21:56:18'),
('AR103', 'Ofertas de videojuegos en Steam', 'Articulos/articulo10-6.php', 'El día de hoy, te acercamos algunas de las ofertas que la plataforma de videojuegos para PC esta llevando a sus usuarios.', 'Articulos/gaming.jpg', 'gaming ofertas steam valve juegos gratis rebajas steam descuentos en videojuegos ofertas en juegos gaming pc computacion informatica epic games resident evil destiny 2 civilization remake konami killing floor crysis 2 crysis 3', '10/06/2020', 102, NULL, '2020-09-05 21:56:18'),
('AR104', 'Twitch recibe denuncias por derechos de autor', 'Articulos/articulo12-6bis.php', 'La plataforma recibió en los últimos días una catarata de demandas basadas en las leyes DMCA, que los intiman a dar de baja contenido o incluso el cierre permanente de canales.', 'Articulos/twitch.jpg', 'twitch streamings informatica seguridad informatica computacion youtube copyright creadores de contenido musica youtubes canales plataforma de streaming demandas a twitch', '12/06/2020', 103, NULL, '2020-09-05 21:56:18'),
('AR105', 'Playstation 5, toda la información en un solo lugar', 'Articulos/articulo12-6.php', 'El evento online de Sony, sobre la nueva consola dejo muchisima información, nosotros te la resumimos en los aspectos más importantes.', 'Articulos/ps5diseño.jpg', 'playstation 5 ps 5 ps5 ps 4 ps4 ps3 ps 3 playstation 4 sony consolas lanzamiento oficial de la playstation 5 juegos videojuegos microsoft gaming xbox serie x xbox one konami japon estados unidos juegos blue-ray square enix ', '12/06/2020', 104, NULL, '2020-09-05 21:56:18'),
('AR106', 'Resident Evil 8, primer trailer de lanzamiento', 'Articulos/articulo13-6.php', 'Luego del evento de la nueva consola de Sony, la Playstation 5, la empresa Capcom lanzó un nuevo trailer para mostrar más detalles de esta entrega.', 'Articulos/resident8evil.jpg', 'playstation 5 ps 5 ps5 ps 4 ps4 ps3 ps 3 playstation 4 playstation 3 capcom resident evil 4 re7 re8 resident evil vii resident evil viii resident evil 8 juegos noticias de videojuegos consolas pc sony', '13/06/2020', 105, NULL, '2020-09-05 21:56:18'),
('AR107', 'Android 11, las principales características', 'Articulos/articulo13-6bis.php', 'Google lanzó la versión 11 de Android, en su modo beta, abierta para ser testeada por usuarios de los smartphones Google Pixel. Entra para ver las mejoras, cambios y detalles más importantes de esta nueva versión.', 'Articulos/android11.png', 'desarrollo desarrolladores programacion programadores google android 11 android q android 10 smartphones celulares telefonia java kotlin noticias tecnologia informatica tablets pc', '13/06/2020', 106, NULL, '2020-09-05 21:56:18'),
('AR108', 'Problemas con la última actualización de Windows 10, y posibles soluciones', 'Articulos/articulo15-6.php', 'La última actualización del sistema operativo mas popular para computadoras personales, recibió hace apenas algunos días, una actualización importante como parche de seguridad de varias vulnerabilidades, pero los problemas no faltaron.', 'Articulos/windows10.jpg', 'desarrollo desarrolladores programacion programadores google android computadoras windows microsoft windows 10 windows 8.1 w10 java kotlin noticias tecnologia informatica tablets pc', '15/06/2020', 107, NULL, '2020-09-05 21:56:18'),
('AR109', 'Playstation 5 anuncia precio y fecha de lanzamiento', 'Articulos/articulo16-6.php', 'Luego del evento digital realizado la semana pasada por Sony, en el cual se mostró el diseño final de la consola, muchas personas quedaron expectantes por el posible precio que tendrá y en que fecha será lanzada, acá te contamos toda la información.', 'Articulos/ps5acce.jpg', 'sony playstation 5 precio ps5 precio informatica juegos consolas ps5 videojuegos noticias de sony noticias de playstation fecha de la playstation 5', '16/06/2020', 108, NULL, '2020-09-05 21:56:18'),
('AR110', 'Whatsapp lleva los pagos entre usuarios a Brasil', 'Articulos/articulo17-6.php', 'El sistema de pagos estará disponible en Brasil, tanto para la mensajería regular como para las pequeñas empresas o negocios. Desde la empresa se anunció que este modo de pago, pronto llegará a otros países.', 'Articulos/telefono1.jpg', 'desarrollo desarrolladores programacion programadores whatsapp facebook instagram php java kotlin pagos en aplicaciones app moviles smartphones telefonos moviles', '17/06/2020', 109, NULL, '2020-09-05 21:56:18');
INSERT INTO `articulos` (`CODIGO`, `NOMBREARTICULO`, `URL`, `DESCRIPCION`, `FOTO`, `TAGS`, `FECHA`, `ID`, `CONTENIDO`, `created_at`) VALUES
('AR111', 'Se confirmaron los AMD Ryzen 3000XT', 'Articulos/articulo17-6bis.php', 'Hace solo algunas horas, se filtró la información sobre los nuevos procesadores de AMD, se conoció que los modelos Ryzen 3000XT, serian lanzados el próximo 7 de julio, junto con las placas base con Chipset A520 y B550.', 'Articulos/amd1.jpg', 'desarrollo desarrolladores programacion programadores pc informatica tecnologia amd intel ryzen 3 ryzen 5 ryzen 7 ryzen 9 ryzen 3000xt ryzen 3000x ryzen 4000 i3 i5 i7 i9 comet lake amd ryzen zen 2 zen 3 7 nanometros computacion threadripper', '17/06/2020', 110, NULL, '2020-09-05 21:56:18'),
('AR112', 'The Last of Us II ya esta disponible', 'Articulos/articulo19-6bis.php', 'Hoy se lanzó la segunda entrega de uno de los videojuegos mas esperados por la comunidad, The Last of Us parte II, exclusivo de Playstation.', 'Articulos/thelast2.jpg', 'videojuegos naughty dog informatica pc playstation 5 playstation 4 ps3 ps4 ps5 sony the last of us II youtubers gameplays games videogames videojuegos ofertas noticias de videojuegos', '19/06/2020', 111, NULL, '2020-09-05 21:56:18'),
('AR113', 'Noticias de videojuegos de la semana', 'Articulos/articulo19-6.php', 'Esta semana te traemos las ofertas de videojuegos para las plataformas mas populares del momento, PC, Nintendo Switch, Playstation, Xbox e incluso para smartphones..', 'Articulos/gaming.jpg', 'pc microsoft xbox 360 xbox one xbox serie x ofertas de videojuegos juegos gratis nintendo switch sony steam epic games uplay valve gta V naughty dog informatica pc playstation 5 playstation 4 ps3 ps4 ps5 the last of us games videogames noticias de videojuegos fx star wars ea ubisoft', '19/06/2020', 112, NULL, '2020-09-05 21:56:18'),
('AR114', 'Se descubre una red de Spyware que ataca usuarios de Google Chrome', 'Articulos/articulo22-6.php', 'la posibilidad de instalar extensiones que permitan mejorar la navegación, es la metodología por la cual algunos grupos intentan crear redes para el robo de datos de usuarios', 'Articulos/hackeo.jpg', 'Google chrome software programacion desarrollo seguridad informatica spyware virus troyanos ransomware hackers hackeo crackeo redes informatica navegadores gusanos de red', '22/06/2020', 113, NULL, '2020-09-05 21:56:18'),
('AR115', 'Elon Musk atrasará el Tesla Battery Day', 'Articulos/articulo22-6bis.php', 'El CEO de SpaceX anunció que, debido a la pandemia, el evento conocido como Tesla Battery Day o Día de la Bateria de Tesla, programado para el 7 de julio, será reprogramado para dentro de un mes', 'Articulos/tesla.jpg', 'tesla hardware spacex elon musk tesla model y hardware autos coches motos motores software programacion desarrollo seguridad informatica empresas eventos finanzas baterias tesla battery day', '22/06/2020', 114, NULL, '2020-09-05 21:56:18'),
('AR116', 'La conferencia virtual de Apple para desarrolladores de este 2020', 'Articulos/articulo23-6.php', 'Apple decidió mostrar en su World Wide Developers Conference, evento conocido como WWDC 2020, varias novedades y anuncios, algunos ya conocidos, otros no tanto, pero toda la información te la resumimos en este artículo.', 'Articulos/apple.jpg', 'apple steve jobs iphone ipad macos osx macintosh iwatch hardware autos coches software programacion desarrollo seguridad informatica empresas eventos finanzas baterias desarrolladores', '23/06/2020', 115, NULL, '2020-09-05 21:56:18'),
('AR117', 'Microsoft anuncia el cierre de Mixer', 'Articulos/articulo24-6.php', 'Luego de una gran inversión por parte de la empresa, en la que incluyó contratos con streamers muy populares como Ninja, se anunció que el próximo 22 de julio, la plataforma dejará de funcionar y se integrará con Facebook Gaming.', 'Articulos/mixer.jpg', 'mixer microsoft facebook gaming xbox serie x software programacion desarrollo seguridad informatica empresas eventos finanzas gaming ninja twitch youtube streaming inversiones plataformas desarrolladores', '24/06/2020', 116, NULL, '2020-09-05 21:56:18'),
('AR118', 'Descuentos en Playstation Store', 'Articulos/articulo25-6.php', 'Sony prepara para esta semana, una serie de descuentos para su tienda online, contando más de 220 títulos, con rebajas cercanas al 70%. En esta sección te contamos cuales son los juegos en rebaja más importantes, para la Playstation 4.', 'Articulos/ps5diseño.jpg', 'sony microsoft facebook gaming xbox serie x ps5 playstation 5 ofertas videojuegos ps4 ps5 playstation 4 software informatica finanzas gaming twitch youtube streaming nintendo ps store rebajas en videojuegos plataformas desarrolladores', '25/06/2020', 117, NULL, '2020-09-05 21:56:18'),
('AR130', 'Los últimos rumores sobre el Samsung Galaxy Note 20', 'Articulos/articulo18-7.php', 'El 5 de agosto es la fecha elegida por la empresa para mostrar el nuevo Samsung Galaxy Note 20, junto con los Smart Watch modelo 3.', 'Articulos/s20ultra.jpg', 'samsung, s20, samsung galaxy note 20, telefonos, smartphones, Celulares, apple, tecnologia, lanzamientos, smartwatch 3 amoled telefonia', '18/7/2020', 118, NULL, '2020-09-05 21:56:18'),
('AR119', 'Boicot contra Facebook y suspensión del sistema de pagos de Whatsapp en Brasil', 'Articulos/articulo26-6.php', 'El gobierno de Brasil no ve con buenos ojos este sistema, desde el Banco Central del país, se le ordenó a Visa y Mastercard, que se ponga un alto a las transacciones.', 'Articulos/facebook.jpg', 'facebook, instagram, pagos por whatsapp, telefonos, smartphones, Celulares, apple, tecnologia, lanzamientos, desarrollo, brasil, finanzas, politica', '26/6/2020', 119, NULL, '2020-09-05 21:56:18'),
('AR120', 'Juegos que saldrán optimizados para la Xbox Series X', 'Articulos/articulo27-6.php', 'Te traemos la lista de títulos que estarán disponibles para la consola, además de la última información sobre la compra de artículos y juegos en las tiendas de Microsoft.', 'Articulos/xboxx.jpg', 'gaming microsoft videojuegos xbox serie x sony ps4 ps5 playstation 5 xbox one juegos consolas lanzamiento juegos optimizados', '27/6/2020', 120, NULL, '2020-09-05 21:56:18'),
('AR121', 'Ofertas de videojuegos en Steam', 'Articulos/articulo27-6bis.php', 'Comienza el verano en el hemisferio norte, una de las temporadas donde Steam suele comenzar a colocar juegos en oferta y como es costumbre, te traemos los juegos más importantes en rebaja.', 'Articulos/steam.jpg', 'gaming videojuegos xbox serie x sony ps4 ps5 playstation 5 juegos pc steam epic games ofertas videojuegos rebajas steam', '27/6/2020', 121, NULL, '2020-09-05 21:56:18'),
('AR122', 'El Reino Unido pide regular las apuestas en videojuegos', 'Articulos/articulo3-7.php', 'La Cámara de los Lores, ha anunciado que pide al gobierno una regulación sobre las “lootboxes”, con la intención de que sea tratado como juego de azar.', 'Articulos/loot.jpg', 'gaming videojuegos lootboxes apuestas skins tradeos fornite overwatch csgo xbox serie x sony ps4 ps5 playstation 5 juegos pc steam epic games', '3/7/2020', 122, NULL, '2020-09-05 21:56:18'),
('AR123', 'Playstation retira su publicidad de Facebook', 'Articulos/articulo4-7.php', 'Una empresa más, se suma al boicot publicitario a la empresa dueña de tres de las redes sociales más importantes. Esta vez, se trata de Sony, que decidió que Playstation ya no sea publicitada en Facebook.', 'Articulos/ps5acce.jpg', 'gaming microsoft videojuegos xbox serie x sony ps4 ps5 playstation 5 xbox one juegos consolas lanzamiento boicot a facebook publicidad', '4/7/2020', 123, NULL, '2020-09-05 21:56:18'),
('AR124', '25 aplicaciones de spyware retiradas de la Google Play Store', 'Articulos/articulo5-7.php', 'Durante la semana, la empresa dueña del sistema operativo Android, eliminó de su tienda aplicaciones que instalaban un software que robaba las credenciales de las cuentas de Facebook.', 'Articulos/android11logo.jpg', 'aplicaciones telefonos smartphones Celulares, apple, tecnologia, android desarrollo seguridad informatica spyware robo de datos virus malware hacking hackers', '5/7/2020', 124, NULL, '2020-09-05 21:56:18'),
('AR125', 'Microsoft se prepara para un evento en julio', 'Articulos/articulo6-7.php', 'La empresa anunció que el próximo 23 de julio, se realizará un evento virtual, donde se mostrarán nuevos títulos y trabajos de la empresa, exclusivos y más información sobre la consola.', 'Articulos/xboxx.jpg', 'gaming microsoft videojuegos xbox serie x sony ps4 ps5 playstation 5 xbox one juegos consolas lanzamiento juegos optimizados', '6/7/2020', 125, NULL, '2020-09-05 21:56:18'),
('AR126', 'TikTok en la mira de todos', 'Articulos/articulo7-7.php', 'La aplicación fue bloqueada en India, junto con casi 60 aplicaciones de origen chino, retirada de Honk Kong, dada la situación social y política, y ahora buscan banearla en los Estados Unidos.', 'Articulos/tiktok.jpg', 'facebook instagram telefonos, smartphones, Celulares, apple, tecnologia, lanzamientos, desarrollo finanzas situacion politica estados unidos honk kong china india tik tok bloqueado', '7/7/2020', 126, NULL, '2020-09-05 21:56:18'),
('AR127', 'Ubisoft prepara un evento en el cual se regalará Watch Dogs 2', 'Articulos/articulo7-7bis.php', 'La desarrolladora de videojuegos, prepara un evento virtual, conocido como Ubisoft Foward, en el cual presentará las últimas noticias y avances de sus trabajos, como Assassins Creed: Valhala y Hyper Scape.', 'Articulos/assassins.jpg', 'gaming videojuegos xbox serie x sony ps4 ps5 playstation 5 juegos pc ubisoft uplay steam epic games watch dogs legion assassins creed Hyper Scape regalos juegos gratis', '7/7/2020', 127, NULL, '2020-09-05 21:56:18'),
('AR128', 'Google Chrome comenzará a consumir menos recursos en sus próximas actualizaciones', 'Articulos/articulo8-7.php', 'El navegador más popular actualmente, es conocido tanto por su sencilla integración con el ecosistema Google como por la cantidad de recursos que consume, por lo que Google intentará cambiar esto.', 'Articulos/googlec.jpg', 'desarrollo javascript programacion desarrolladores programadores google chrome v8 actualizaciones navegadores web browsers firefox edge', '8/7/2020', 128, NULL, '2020-09-05 21:56:18'),
('AR129', 'Luego de separarse de Intel, Apple quiere independizarse completamente', 'Articulos/articulo14-7.php', 'Luego de romper la sociedad con Intel, la empresa liderada por Tim Cook decidió que dejará de utilizar placas gráficas de fabricación AMD. A finales de este año, saldrán a la venta las primeras portatiles de la empresa, potenciadas por el procesador A14.', 'Articulos/apple.jpg', 'apple intel amd procesadores cpus gpus ryzen a14 arm arquitectura arm navi macbooks macintosh computadoras apple nuevos procesadores', '14/7/2020', 129, NULL, '2020-09-05 21:56:18'),
('AR129', 'Ubisoft presenta un nuevo Far Cry', 'Articulos/articulo16-7.php', 'La empresa mostró un trailer sobre su nuevo juego, que saldrá a comienzos de 2021, y confirmó a un actor de Breaking Bad y The Mandalorian, como villano de esta entrega.', 'Articulos/farcry6.jpg', 'gaming videojuegos xbox serie x sony ps4 ps5 playstation 5 juegos pc ubisoft uplay steam epic games watch dogs legion assassins creed Hyper Scape regalos far cry 5 far cry 6 farcry6', '16/7/2020', 130, NULL, '2020-09-05 21:56:18'),
('AR130', 'Los últimos rumores sobre el Samsung Galaxy Note 20', 'Articulos/articulo18-7.php', 'El 5 de agosto es la fecha elegida por la empresa para mostrar el nuevo Samsung Galaxy Note 20, junto con los Smart Watch modelo 3. En este día, la empresa anunciará el lanzamiento de esta gama, confirmando su fecha de salida al mercado, precio, y algunas características sobre las que ya se están hablando, entrá para ver cuales son los últimos rumores de los nuevos terminales.', 'Articulos/s20ultra.jpg', 'samsung galaxy note 20 smart watch modelo 3 telefonos reviews smartphones telefonia moviles s20 apple', '18/7/2020', 131, NULL, '2020-09-05 21:56:18'),
('AR131', 'Noticias de videojuegos, Rocket League y FIFA 21', 'Articulos/articulo21-7.php', 'Esta semana, Epic Games anunció que el juego Rocket League, estará disponible, de forma definitiva en su plataforma, y de manera gratuita. Esto significa, que el juego será Free To Play para siempre, pero también exclusivo para la plataforma de videojuegos, la cual compró hace algún tiempo el estudio que desarrolla el juego. También te contamos cuando saldrá el trailer sobre FIFA 21.', 'Articulos/fifa.jpg', 'videojuegos steam fifa epic games fornite rocket league ea sports free to play valve gaming pc gaming tencent trailer fifa 21', '21/7/2020', 132, NULL, '2020-09-05 21:56:18'),
('AR132', 'Luego de anunciar la salida de Far Cry 6, su predecesor entra en rebaja para PS', 'Articulos/articulo22-7bis.php', 'Hace solo días, Ubisoft mostró el tráiler de su próxima entrega para la saga Far Cry, su sexta entrega junto con el actor Esposito, conocido por su papel en Breaking Bad y The Mandalorian, como su principal antagonista. Como parte de esta campaña la empresa colocó en PS Store, en rebaja Far Cry 5, el último juego de la saga.', 'Articulos/farcry5.jpg', 'videojuegos steam ubistoft far cry 5 far cry 6 rebajas ofertas pc gaming uplay ps playstation fc5 fc6 ps store', '22/7/2020', 133, NULL, '2020-09-05 21:56:18'),
('AR133', 'Asus confirma la salida del ROG Gaming Phone 3', 'Articulos/articulo22-7.php', 'El gigante de la tecnología, había anunció hace algunas semanas la salida de un nuevo dispositivo móvil, orientado al gaming, con características bastante únicas, como un teléfono con el procesador Qualcomm Snapdragon 865 y una memoria de hasta 16 GB.', 'Articulos/rogasus.jpg', 'gaming phone asus tecnologia smartphone telefonos gamer asus tencent asus rog gaming phone telefono gaming asus', '22/7/2020', 134, NULL, '2020-09-05 21:56:18'),
('AR134', 'Rebajas en Steam de finales de julio', 'Articulos/articulo24-7.php', 'En este artículo te acercamos una lista de los juegos en oferta que la plataforma ha colocado para finales de este mes, hasta el 27 de julio, con rebajas interesantes que podés aprovechar. En esta ocasión Steam coloca varios géneros en ofertas interesantes para todos los gustos, y nosotros te acercamos la lista con los títulos más destacados, junto con el enlace a la lista completa.', 'Articulos/capturaSteam1.png', 'rebajas steam ofertas juegos gratis juegos en oferta rebajas en steam valve civilization vI age of empires fable assassins creed ubisoft', '24/7/2020', 135, NULL, '2020-09-05 21:56:18'),
('AR135', 'Intel en una semana muy movida', 'Articulos/articulo25-7.php', 'En los últimos meses, la empresa liderada por Bob Swan, fue noticia por diferentes razones, algunas buenas y otras no tan placenteras para la compañía. Sus acciones suben, pero sus competidores lo acorralan, dado que la competencia con AMD parece estar favoreciendo y mucho a la empresa liderada por Lisa Su.', 'Articulos/intel02.jpg', 'apple intel amd procesadores cpus gpus ryzen a14 INTEL i3 i5 i7 7nm 10nm arm navi nvidea microprocesadores computacion computadoras tecnologia microchips informatica', '25/7/2020', 136, NULL, '2020-09-05 21:56:18'),
('AR136', 'Un nuevo Motorola, esta vez más completo', 'Articulos/articulo25-7bis.php', 'Una de las principales críticas a este fabricante de smartphones es que sus modelos suelen tener pocas características y utilidades a un precio demasiado alto, cuando su competencia ofrece teléfonos a un valor inferior y con mejor resultado. Parece que Motorola no hace oídos sordos a las críticas, y se planteó crear un Smartphone que pueda competir contra nuevas marcas como Xiaomi en la Argentina, y con otros como el grupo OnePlus a nivel internacional.', 'Articulos/5g5.jpg', 'apple smartphones xiaomi oneplus telefonia telefonos motorola g5g moto g5g camaras tecnologia microchips informatica', '25/7/2020', 137, NULL, '2020-09-05 21:56:18'),
('AR137', 'Mi True Wireless Earbuds de Xiaomi', 'Articulos/articulo28-7.php', 'En esta ocasión, te traemos una review para un producto que nos han preguntado. Los auriculares inalámbricos son cada vez más populares, y dado que muchas marcas de telefonía no incluyen Jack de auriculares tradicional, es importante seleccionar un producto que sea bueno. Por ello, en este artículo podrás conocer los aspectos más importantes de los Earbuds de Xiaomi.', 'Articulos/earb2.png', 'apple smartphones xiaomi earbuds oneplus auriculares bluetooth inalambricos mi true wireless earbuds airpods telefonia telefonos motorola g5g moto g5g camaras tecnologia microchips informatica', '28/7/2020', 138, NULL, '2020-09-05 21:56:18'),
('AR138', 'Twitter banea cuentas acusadas de Fake News', 'Articulos/articulo29-7.php', 'Luego de la polémica en la cual varios tweets de Donald Trump fueran borrados de la plataforma, por contener noticias falsas o incitación a la violencia, la plataforma decidió continuar bloqueando y dando de baja cuentas que caigan en el mismo accionar. La intención, además de limpiar Twitter de estos usuarios, es frenar la violencia que se vive en las calles.', 'Articulos/twitter.jpg', 'redes sociales twitter jack dorsey polemica cuentas spam fake news facebook donald trump estados unidos baneo noticias falsas', '29/7/2020', 139, NULL, '2020-09-05 21:56:18'),
('AR139', 'CAT, el fabricante de herramientas y vehículos de obra, muestra su teléfono con cámara térmica', 'Articulos/articulo29-7bis.php', 'Para mucha gente, el Smartphone perfecto es uno delgado, con mucha resolución de pantalla, enfocado en un estilo que siga la norma, como viene haciéndolo Samsung, Apple y otras marcas. Sin embargo, no todo el mundo busca eso en un teléfono, sino que existen más necesidades, como la resistencia. El teléfono CAT S62 Pro es uno de los celulares creado para durar, no pensando en la estética general del smartphone, sino en que cuente con una gran durabilidad y soporte a condiciones extremas.', 'Articulos/cats62.jpg', 'apple smartphones xiaomi oneplus telefonia telefonos motorola camara termica cat celulares para profesionales camaras tecnologia microchips informatica', '29/7/2020', 140, NULL, '2020-09-05 21:56:18'),
('AR140', 'Mark Zuckerberg, Tim Cook, Jeff Bezos y Sundar Pichai ante el congreso norteamericano', 'Articulos/articulo30-7bis.php', '¿Puede una empresa competir realmente contra Amazon, Google, Facebook o Apple? ¿Y, por otro lado, estas empresas están intentando destruir a sus competidores y borrarlos del mercado? Este es el debate al que se someten las cuatro empresas de internet, ante la justicia de los Estados Unidos y la Union Europea, acusados de técnicas de competencia desleales.', 'Articulos/juicioInternet.jpg', 'internet tecnologia empresas finanzas congreso estados unidos facebook amazon apple google Mark Zuckerberg, Tim Cook, Jeff Bezos y Sundar Pichai juicios spotify eu union europea leyes de internet', '30/7/2020', 141, NULL, '2020-09-05 21:56:18'),
('AR141', 'El FBI detuvo a un posible responsable por el hackeo a Twitter', 'Articulos/articulo2-8.php', 'Hace apenas unos días, varias cuentas de famosos y personalidades habían sido utilizadas para pedir donaciones vía Bitcoin. Cuentas como la de Bill Gates, Barak Obama, Elon Musk, Jeff Bezos, Mike Bloomberg, Kim Kardashian o Warren Buffet fueron utilizadas para realizar la estafa, que según las autoridades recaudo cerca de 100 mil dólares en un día. ¿El responsable? La policía de los Estados Unidos detuvo a un joven de 17 años.', 'Articulos/twitter.jpg', 'internet tecnologia empresas fbi hackeo estafas phishin seguridad informatica twitter famosos celebridades estados unidos facebook Bitcoin criptomonedas robos Bill Gates, Barak Obama, Elon Musk, Jeff Bezos, Mike Bloomberg Graham Ivan Clark', '2/8/2020', 142, NULL, '2020-09-05 21:56:18'),
('AR142', 'Noticias desde el espacio: Space Crew Dragon emprende el regreso', 'Articulos/articulo2-8bis.php', 'Luego de pasar más de dos meses en la Estación Espacial Internacional, los astronautas que tripularon el Space Crew Dragon, volverán a la tierra. La nave despertó en muchos un gran interés, por tratarse del primer viaje desarrollado por una empresa privada, SpaceX, creada por el famoso millonario Elon Musk.', 'Articulos/spacex.jpg', 'espacio exploracion espacial spacex space crew dragon argentina astronautas tecnologia elon musk viaje espacial iss estacion espacial internacional arsat argentina satelites argentinos', '2/8/2020', 143, NULL, '2020-09-05 21:56:18'),
('AR143', '¿Puede ser baneado TikTok en los Estados Unidos?', 'Articulos/articulo3-8.php', 'Hace algunas semanas, el secretario de estado de E.E. U.U. anunció que, debido a la ley de seguridad nacional sancionada en China, una empresa estaría obligada a entregar datos de sus usuarios de forma masiva al gobierno del país de Asia, por lo que la posibilidad de bloquear la aplicación estaba presente. En los últimos días, el tema volvió a ser relevante cuando el presidente Trump anunció que estaban muy cerca de tomar una decisión al respecto.', 'Articulos/tiktok.jpg', 'microsoft tik tok estados unidos donald trump china guerra comercial ley de seguridad nacional honk kong google apple huawei empresas chinas', '3/8/2020', 144, NULL, '2020-09-05 21:56:18'),
('AR144', 'Todo lo que dejo el evento de Samsung desde Corea, con nuevos Smartphones, Tablets y más', 'Articulos/articulo5-8.php', 'Es muy difícil coordinar un evento en medio de una pandemia, pero las empresas parecen haber encontrado el rumbo en eventos virtuales o semi-presenciales, con poca prensa y ningún visitante externo. Samsung se suma asi a la lista de empresas con anuncios de este año, con el lanzamiento de varios dispositivos nuevos, entre los cuales se destaca el Samsung Note 20, Tablets nuevas, e incluso auriculares inalámbricos.', 'Articulos/samsung.jpg', 'samsung smartphones earbuds tablets tecnologia anuncios telefonos telefonia auriculares inalambricos Samsung galaxy note 20 samsung note 20 samsung galaxy tab s7 samsung tab s7 samsung tab s7+ s7plus note plus', '5/8/2020', 145, NULL, '2020-09-05 21:56:18'),
('AR145', 'Luego de la polémica con TikTok, varias empresas se interesan en comprarla', 'Articulos/articulo10-8.php', 'Hace algunos días se hablaba de lo incierto que es el futuro de la red social de origen chino, con intenciones por parte del gobierno de los Estados Unidos por bloquearla definitivamente, con acusaciones de que sus datos son usados para espionaje, entre otras cosas. Sin embargo, varias empresas mostraron interés en adquirir parte de las acciones de la compañía, o la aplicación en su totalidad, como es el caso de Microsoft y Tiwtter.', 'Articulos/twitter.jpg', 'tiktok microsoft desea comprar tiktok twitter desea comprar tiktok jack dorsey millones dolares empresas finanzas guerra comercial china estados unidos', '10/8/2020', 146, NULL, '2020-09-05 21:56:18'),
('AR146', 'Ofertas semanales de Playstation para el mes de agosto, hasta el jueves 20', 'Articulos/articulo12-8.php', 'Mientras muchos esperan ansiosos la llegada de la nueva Playstation 5 a finales de este año, Sony decide colocar en oferta varios títulos para este mes, siguiendo la costumbre de este año que ha tenido importantes regalos y descuentos para todas las plataformas de videojuegos. Hasta el 20 de agosto, es decir durante 8 días, podes aprovechar los descuentos que te contamos en este artículo.', 'Articulos/ps5diseño.jpg', 'ps5 playstation 5 playstation 4 ps4 ps store playstation store juegos regalos rebajas juegos de playstation 4 en rebaja ofertas gaming consolas videojuegos', '12/8/2020', 147, NULL, '2020-09-05 21:56:18'),
('AR147', 'Epic Games le declara la guerra a Google y a Apple', 'Articulos/articulo19-8.php', 'Ya no será posible descargar Fornite desde la plataforma Google Play Store, ni desde la App Store de iOS. Epic Games viene enfrentándose a otros gigantes de la tecnología, como Steam, en el mundo de los videojuegos ofreciendo mejores contratos a los desarrolladores, y acaparando juegos exclusivos, aunque no es una empresa del todo aceptada en la comunidad. Ahora, tiene otro frente de batalla, las dos empresas de tecnología móvil más importantes, Google y Apple.', 'Articulos/apple-epic-google.jpg', 'ps5 ps4 playstation store juegos regalos rebajas juegos de playstation 4 en rebaja ofertas gaming consolas videojuegos epic games apple fornite parodia apple google play store android ios fornite deja de estar disponible en android y apple unreal engine empresas', '19/8/2020', 148, NULL, '2020-09-05 21:56:18'),
('AR148', 'Robos de cuentas de Whatsapp, haciéndose pasar por soporte técnico', 'Articulos/articulo20-8.php', 'Este año se caracterizó por tener un aumento muy alto en los casos de estafas y hackeos, en todas partes del mundo, tanto en empresas multinacionales, como en todo tipo de organizaciones. Hace pocos días, se denunció que una nueva forma de estafa estaba teniendo lugar por medio de Whatsapp. Los criminales se hacían pasar por miembros de la empresa, con la excusa de ser parte del soporte técnico.', 'Articulos/whatsapp.png', 'Whatsapp servicio tecnico estafas phishing scammers seguridad informatica facebook instagram redes sociales hackers crackers', '20/8/2020', 149, NULL, '2020-09-05 21:56:18'),
('AR149', 'Fall Guys rompe record de ventas en su lanzamiento.', 'Articulos/articulo21-8.php', 'El juego fue muy bien aceptado por la comunidad, generando buenas reseñas, y llenando las plataformas de streaming con muchos creadores de contenido mostrando el juego. El juego superó en su lanzamiento, números como los de GTA V, Rainbow Six Seige y Destiny 2. En la plataforma de Playstation 4, el juego se vendió a más de 8 millones de jugadores, algo que se vio favorecido porque fue regalado por la suscripción a Playstation Plus.', 'Articulos/fallguys.jpg', 'Fall Guys rompe record de ventas en su lanzamiento epic games steam ofertas videojuegos games videogames consolas e3 eventos lanzamientos', '21/8/2020', 150, NULL, '2020-09-05 21:56:18'),
('AR150', 'Denuncian que TikTok accedía a las direcciones físicas de sus usuarios.', 'Articulos/articulo20-8bis.php', 'Por medio de un defecto en la seguridad de Android, el sistema operativo más popular para dispositivos móviles, hasta hace algunos meses, era posible acceder a la dirección MAC de los teléfonos por medio de una aplicación. Según un artículo de The Wall Street Journal, TikTok aprovechaba esto para acceder a la dirección física de los dispositivos en los que era instalado. Además, el gobierno japonés señaló que un cambio en los dueños de la empresa cambiaría la preocupación hacía la seguridad y el manejo de los datos por parte de la empresa.', 'Articulos/tiktok2.jpg', 'tiktok microsoft desea comprar tiktok twitter desea comprar tiktok jack dorsey millones dolares empresas finanzas guerra comercial china estados unidos gobierno de japon robo de datos robo de direcciones mac tiktok acusada de acceder a direcciones fisicas e historial de sus usuarios', '21/8/2020', 151, NULL, '2020-09-05 21:56:18'),
('AR151', 'Microsoft y Blackberry quieren volver al mercado de los Smartphone', 'Articulos/articulo23-8.php', 'Hace mucho tiempo que ambas empresas desistieron en sus intentos por competir contra los gigantes en el ámbito de los dispositivos móviles, como Samsung y Apple, que cada vez dejan menos margen de mercado para otras empresas. Surface Duo es el regreso de la empresa que fundó en su momento Bill Gates, a este mercado, con un sistema operativo Android, y doble pantalla. Por otro lado, Blackberry decidió crear un nuevo teléfono, muy distinto a lo que se ve en estos momentos, con verdadero teclado físico.', 'Articulos/surface-duo.jpg', 'celulares smartphones telefonia empresas tecnologia telefonos samsung tablets tabletas tablet Microsoft y Blackberry quieren volver al mercado de los Smartphone doble pantalla Surface Duo huawei lanzamientos reviews', '23/8/2023', 152, NULL, '2020-09-05 21:56:18'),
('AR152', 'DC Fandome: Trailers de una nueva generación de películas y juegos', 'Articulos/articulo23-8bis.php', 'Warner Bros mostró varios teasers de las nuevas películas que se vienen en el universo de superheroes DC, así como tambien una mini serie, y un nuevo videojuego de los creadores de Batman: Arkham series, llamado Suicide Squad: Kill the Justice League. ¡Entrá para ver todos los trailers!', 'Articulos/dc.jpg', 'DC FanDome Shazam! Fury of the Gods y la secuela de Aquaman 2 trailers universo de superhéroes de DC Suicide Squad: Kill the Justice League the batman rober patinson wonder woman gal gadot the justice league dc juegos videojuegos warner', '23/8/2023', 153, NULL, '2020-09-05 21:56:18'),
('AR153', 'Más títulos confirmados en el universo de superhéroes de DC', 'Articulos/articulo25-8.php', 'Luego de la DC FanDome que nos dejó diversos trailers y avances de sus nuevas películas, como The Batman, y Wonder Woman 84, un avance de su nuevo juego Suicide Squad – Kill The Justice League, y también una mini serie de 4 capítulos, Warner confirmó vía Twitter dos películas en producción, Shazam! Fury of the Gods y la secuela de Aquaman, con fechas confirmadas.', 'Articulos/dc.jpg', 'DC FanDome Shazam! Fury of the Gods y la secuela de Aquaman 2 trailers universo de superhéroes de DC Suicide Squad: Kill the Justice League the batman rober patinson wonder woman gal gadot the justice league dc juegos videojuegos warner', '25/8/2020', 154, NULL, '2020-09-05 21:56:18'),
('AR154', 'Páginas web, canales, y otros lugares con tutoriales gratuitos para desarrolladores', 'Articulos/articuloPaginasAprenderCodigo.php', 'Para todas aquellas personas interesadas en aprender nuevas tecnologías, o que deseen introducirse desde cero en el mundo del desarrollo de software, sitios web, juegos y todo tipo de programas, les acercamos una lista con cursos online, de acceso gratuito y sencillo más populares. Si te interesa la programación te recomendamos que visites la lista para descubrir canales de Youtube y páginas web dedicadas a la enseñanza de estas tecnologias.', 'Articulos/codigo1.jpg', 'desarrolladores desarrollo web developers sitios para aprender programacion cursos gratis sitios de programacion tutoriales java gratis tutorial python gratis curso php gratis programing crear videojuegos unity c# html javascript aprender programacion programar', '27/8/2020', 155, NULL, '2020-09-05 21:56:18'),
('AR155', 'Hitman y Shadowrun gratis en Epic Games Store, durante una semana, hasta el 3 de septiembre', 'Articulos/articulo28-8.php', 'Como cada semana, Epic Games regala en su plataforma de videojuegos, uno o dos títulos para todos aquellos que entren a reclamar una copia de forma permanente. No siempre se trata de juegos de renombre o títulos aclamados, aunque en algunas ocasiones, la empresa ofrece juegos como GTA V de manera gratuita, lo cual genera un gran revuelo y espectativa en la comunidad del gaming. Esta semana, la oferta es de Shadowrun Collection y de Hitman. Entrá para enterarte cuanto dura la oferta y como reclamar ambos juegos.', 'Articulos/epicgames.png', 'epic games steam ofertas videojuegos games videogames consolas e3 eventos lanzamientos regalos en epic games juegos gratis hitman gratis Shadowrun gratis en Epic Games Store', '28/8/2020', 156, NULL, '2020-09-05 21:56:18'),
('AR156', 'Fallece a los 43 años, Chadwick Boseman, protagonista de Black Panther', 'Articulos/articulo29-8.php', 'Nos toca informar este fin de semana con gran pesar, que el actor que protagonizó Black Panther, rol por el cual generó una gran cantidad de fans y seguidores, Chadwick Boseman falleció a los 43, tras una larga batalla contra el cáncer de colon.', 'Articulos/chadwick-boseman.jpg', 'marvel peliculas hollywood disney dc Chadwick Boseman black panther II Chadwick Boseman por un cáncer de colon Chadwick Boseman por un cancer de colon', '29/8/2020', 157, NULL, '2020-09-05 21:56:18'),
('AR157', 'Hoy se lanza al espacio un nuevo satélite argentino', 'Articulos/articulo30-8.php', 'Hoy, luego de algunos contratiempos que obligaron a reprogramar la fecha, se lanzará nuevamente desde Cabo Cañaveral, en Florida, un satélite argentino, al que se lo conoce como Saocom 1B, desarrollado también por la empresa de Elon Musk. El satélite tiene como objetivo proporcionar datos meteorológicos y sobre el estado de la superficie a la región pampeana, una ventaja que brindará a la agricultura de la zona información muy valiosa.', 'Articulos/Saocom.jpg', 'tecnologia elon musk spacex space x tesla satelite argentino Saocom18 Saocom 18 lanzamientoo iis estacion espacial internacional exploracion internacion', '30/8/2020', 158, NULL, '2020-09-05 21:56:18'),
('AR159', 'Nvidea anunció el lanzamiento de su nueva generación de tarjetas gráficas', 'Articulos/articulo2-9.php', 'La empresa ya venía siendo foco de rumores desde comienzos de este año, y se decía que una nueva generación de tarjetas gráficas estaba próxima, con una posible fecha de salida a finales del año. Finalmente, en su evento, Nvidea mostró las nuevas RTX 3070, 3080, y 3090, no sin sorpresas. Entrá para enterarte de su potencia, especificaciones y también el precio.', 'Articulos/rtx3000.jpg', 'intel amd ryzen procesadores computacion informatica tecnologia internet empresas nvidea rtx3000 rtx3070 rtx3080 rtx3090 RTX tercera generacion rtx 3070 rtx 3080 rtx 3090 micron nuevas tarjetas graficas nvidea gpus placas de video geforce', '2/9/2020', 159, NULL, '2020-09-05 21:56:18'),
('AR160', 'Facebook bloqueará los anuncios políticos una semana antes de las elecciones', 'Articulos/articulo3-9.php', 'Dado que se teme que las publicaciones realizadas con tinte político, o con intenciones de publicitar a uno u a otro candidato, no podrían ser chequeadas a tiempo antes del día de las elecciones, la plataforma decidió bloquear estos posteos, afirmando que intentará proteger la integridad de las elecciones. Además, brindará información al votante en las cabeceras de noticias de los usuarios, como votar, y donde ver los resultados de los comicios.', 'Articulos/facebook.jpg', 'facebook empresas donald trump mark zuckergber twitter polemica tweets posteos elecciones en los estados unidos', '3/9/2020', 160, NULL, '2020-09-05 21:56:18'),
('AR161', 'CD Projectk RED anunció The Witcher 3 para PS5, Xbox Series X y PC', 'Articulos/articulo4-9.php', 'La empresa anunció vía Twitter, que la nueva generación de consolas podrá disfrutar del juego, tanto para la consola de Sony como para la de Microsoft, junto con sus expansiones, las cuales son Blood and Wine y Hearts of Stone.', 'Articulos/the-witcher.jpg', 'gaming gamers the witcher henry cavil juegos videojuegos videogames gaming actualizacion the witcher 3 hearts of stone blood and wine ofertas ', '4/9/2020', 161, NULL, '2020-09-05 21:56:18');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `articulos`
--
ALTER TABLE `articulos`
  ADD PRIMARY KEY (`ID`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `articulos`
--
ALTER TABLE `articulos`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=162;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
